### ISSUE TITLE
[Meta] Fix ignored unit tests

### ISSUE THREAD

**Issue by kdy1** [dudykr/stc#418]
`find . -type f -name ".*" | sort | sed -e 's/^/- [ ] /'` from `./crates/stc_ts_file_analyzer`

## List

- [ ] ./tests/errors/conformance/types/intersection/withUnionConstraint/.1.ts
- [ ] ./tests/pass-only/conformance/ambient/ambientExternalModuleInsideNonAmbient/.1.ts
- [ ] ./tests/pass-only/conformance/classes/mixinClassesAnnotated/.1.ts
- [ ] ./tests/pass-only/conformance/classes/propertyMemberDeclarations/accessorsOverrideProperty9/.1.ts
- [ ] ./tests/pass-only/conformance/controlwFlow/controlFlowForOfStatement/.1.ts
- [ ] ./tests/pass-only/conformance/controlwFlow/controlFlowForStatement/.1.ts
- [ ] ./tests/pass-only/conformance/es6/Symbols/symbolProperty61/.1.ts
- [ ] ./tests/pass-only/conformance/es6/Symbols/symbolType16/.1.ts
- [ ] ./tests/pass-only/conformance/es6/destructuring/missingAndExcessProperties/.1.ts
- [ ] ./tests/pass-only/conformance/generators/generatorReturnContextualType/.1.ts
- [ ] ./tests/pass-only/conformance/generators/generatorReturnContextualType/.2.ts
- [ ] ./tests/pass-only/conformance/generators/generatorReturnContextualType/.3.ts
- [ ] ./tests/pass-only/conformance/statements/VariableStatements/validMultipleVariableDeclarations/.1.ts
- [ ] ./tests/pass-only/conformance/types/conditional/conditionalTypes2/.1.ts
- [ ] ./tests/pass-only/conformance/types/conditional/conditionalTypes2/.2.ts
- [ ] ./tests/pass-only/conformance/types/conditional/conditionalTypes2/.3.ts
- [ ] ./tests/pass-only/conformance/types/literal/templateLiteralTypesPatterns/.1.ts
- [ ] ./tests/pass/class/constructor/overloading/.optional-params-1.ts
- [ ] ./tests/pass/class/member/accessibility/privateClassPropertyAccessibleWithinNestedClass/.1.ts
- [ ] ./tests/pass/class/nested/.async-await-1.ts
- [ ] ./tests/pass/class/nested/private/.1.ts
- [ ] ./tests/pass/class/nested/protected/.1.ts
- [ ] ./tests/pass/class/private/field/privateNameFieldDestructuredBinding/.1.ts
- [ ] ./tests/pass/controlFlow/guard/assertions/.1.ts
- [ ] ./tests/pass/controlFlow/guard/assertions/.2.ts
- [ ] ./tests/pass/controlFlow/guard/assertions/.3.ts
- [ ] ./tests/pass/controlFlow/whileStmt/.simple-1.ts
- [ ] ./tests/pass/exprs/array/.destructuring.ts
- [ ] ./tests/pass/exprs/call/genericCallWithGenericSignatureArguments/.1.ts
- [ ] ./tests/pass/exprs/call/genericCallWithGenericSignatureArguments/.2.ts
- [ ] ./tests/pass/exprs/class/.simple-1.ts
- [ ] ./tests/pass/exprs/lit/number/.bin-1.ts
- [ ] ./tests/pass/exprs/new/promise/finally/.1.ts
- [ ] ./tests/pass/exprs/object/property/.string-named-numerics-1.ts
- [ ] ./tests/pass/exprs/object/spread/typeParam/.2.ts
- [ ] ./tests/pass/exprs/object/spread/typeParam/.5.ts
- [ ] ./tests/pass/exprs/object/spread/typeParam/.6.ts
- [ ] ./tests/pass/exprs/object/this/.2-1.ts
- [ ] ./tests/pass/exprs/object/this/.2-2.ts
- [ ] ./tests/pass/exprs/object/this/thisTypeInObjectLiterals2/.2.ts
- [ ] ./tests/pass/exprs/typeAssertion/.1.ts
- [ ] ./tests/pass/exprs/typeAssertion/.10.ts
- [ ] ./tests/pass/exprs/typeAssertion/.5.ts
- [ ] ./tests/pass/exprs/typeAssertion/.6.ts
- [ ] ./tests/pass/exprs/typeGuards/typeGuardOfFromPropNameInUnionType/.7.ts
- [ ] ./tests/pass/typeRelationships/typeInference/genericCallWithGenericSignatureArguments/.11.ts
- [ ] ./tests/pass/typeRelationships/typeInference/genericCallWithGenericSignatureArguments/.2.ts
- [ ] ./tests/pass/typeRelationships/typeInference/genericCallWithGenericSignatureArguments/.7.ts
- [ ] ./tests/pass/typeRelationships/typeInference/genericCallWithGenericSignatureArguments/.9.ts
- [ ] ./tests/pass/types/conditional/conditionalTypes1/.1.ts
- [ ] ./tests/pass/types/conditional/conditionalTypes1/.2.ts
- [ ] ./tests/pass/types/conditional/conditionalTypes1/.5.ts
- [ ] ./tests/pass/types/conditional/conditionalTypes1/.6.ts
- [ ] ./tests/pass/types/conditional/conditionalTypes1/.7.ts
- [ ] ./tests/pass/types/conditional/conditionalTypes1/.8.ts
- [ ] ./tests/pass/types/conditional/conditionalTypes1/.9.ts
- [ ] ./tests/pass/types/inference/contextualSignatureInstantiation/.1.ts
- [ ] ./tests/pass/types/inference/generic/contextual/.contextual-1-2.ts
- [ ] ./tests/pass/types/inference/generic/contextual/.contextual-1.ts
- [ ] ./tests/pass/types/inference/generic/contextual/.contextual-2-1.ts
- [ ] ./tests/pass/types/inference/generic/contextual/.contextual-2-3.ts
- [ ] ./tests/pass/types/inference/generic/contextual/.contextual-2-4.ts
- [ ] ./tests/pass/types/inference/generic/contextual/.contextual-3-1.ts
- [ ] ./tests/pass/types/inference/generic/contextual/.contextual-3-2.ts
- [ ] ./tests/pass/types/inference/generic/contextual/.contextual-3-4.ts
- [ ] ./tests/pass/types/inference/generic/contextual/.contextual-4-1.ts
- [ ] ./tests/pass/types/inference/generic/contextual/.contextual-4-2.ts
- [ ] ./tests/pass/types/inference/object/.typeArgumentInferenceWithObjectLiteral-1.ts
- [ ] ./tests/pass/types/intersection/intersectionTypeInference2/.1.ts
- [ ] ./tests/pass/types/literal/.literalTypes2-1.ts
- [ ] ./tests/pass/types/literal/.numericStringLiteralTypes.ts
- [ ] ./tests/pass/types/mapped/.4-3.ts
- [ ] ./tests/pass/types/mapped/.6.ts
- [ ] ./tests/pass/types/scoping/.local-1.ts
- [ ] ./tests/pass/types/scoping/.local-2.ts
- [ ] ./tests/pass/types/scoping/.local-3.ts
- [ ] ./tests/pass/types/scoping/.local-5.ts
- [ ] ./tests/pass/types/this/thisType/.1.ts
- [ ] ./tests/pass/vars/forOf/hoisting/.1.ts
- [ ] ./tests/pass/vars/forOf/hoisting/.4.ts
- [ ] ./tests/pass/vars/forOf/hoisting/.6.ts
- [ ] ./tests/pass/vars/forOf/hoisting/.7.ts
- [ ] ./tests/pass/vars/forOf/hoisting/.8.ts
- [ ] ./tests/pass/vars/order/.1.ts
- [ ] ./tests/pass/vars/order/.2.ts
- [ ] ./tests/pass/vars/typeAnn/fn/.1.ts
- [ ] ./tests/pass/vars/typeAnn/fn/.2.ts
- [ ] ./tests/tsc/types/builtin/generator/bad/.1.ts
- [ ] ./tests/tsc/types/builtin/generator/bad/.1.tsc-errors.json
- [ ] ./tests/visualize/controlFlow/forStmt/.simple-1.ts
- [ ] ./tests/visualize/controlFlow/ifStmt/.simple-1.ts
- [ ] ./tests/visualize/exprs/assign/typeNarrowing/.seq-1.ts
- [ ] ./tests/visualize/exprs/assign/typeNarrowing/.simple-1.ts
- [ ] ./tests/visualize/exprs/class/static/typeArgumentInferenceWithClassExpression2/.1.ts
- [ ] ./tests/visualize/exprs/object/method/.normalization-1.ts
- [ ] ./tests/visualize/types/generic/.pinning-1.ts
- [ ] ./tests/visualize/types/inference/generic/object/.infer-then-reuse-1.ts
- [ ] ./tests/visualize/types/inference/generic/object/.infer-then-reuse-2.ts
- [ ] ./tests/visualize/types/inference/generic/rest/.2.ts
- [ ] ./tests/visualize/types/inference/instantiation/signature/.1.ts
- [ ] ./tests/visualize/types/inference/instantiation/signature/.2.ts
- [ ] ./tests/visualize/types/inference/instantiation/signature/.3.ts
- [ ] ./tests/visualize/types/typeLit/call/.hiding-1.ts
- [ ] ./tests/visualize/types/typeLit/constructor/.hiding-1.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-1/.builtin-object-in-closure-param-2.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-1/.builtin-object-in-closure-param-3.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-1/.builtin-object-in-closure-param.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-1/.builtin-object-in-closure-return.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-1/.union-in-closure-return.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-2/.type-lit-1.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-2/.type-lit-2-compatible.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-first/.builtin-object-in-closure-return.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-first/.union-in-closure-return.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-only/.builtin-object-in-closure-return.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-only/.string-in-closure-return.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-only/.union-in-closure-return-1.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/closure-only/.union-in-closure-return-2.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/contextualSignatureInstantiation/.1.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/contextualSignatureInstantiation/.2-1-1.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/contextualSignatureInstantiation/.2-1.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/contextualSignatureInstantiation/.2.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/contextualSignatureInstantiation/.3-2.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/contextualSignatureInstantiation/.3.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/lab2/.10.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/lab2/.2.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/lab2/.3.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/lab2/.4.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/lab2/.5.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/lab2/.6.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/nested-closure/.builtin-object-in-closure-return.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/nested-closure/.string-in-closure-return.ts
- [ ] ./tests/visualize/types/typeRelationShips/typeInference/nested-closure/.union-in-closure-return.ts
- [ ] ./tests/visualize/vars/forOf/hoisting/.2.ts
- [ ] ./tests/visualize/vars/forOf/hoisting/.3.ts
- [ ] ./tests/visualize/vars/forOf/hoisting/.5.ts
- [ ] ./tests/visualize/vars/forOf/hoisting/.9.ts

**Comment by kdy1** [comment]
Closing in favor of a script-based approach
